#' Combine multiple column definitions into a single named list for use in a Reactable table
#'
#' The \code{combined_named_lists} function combines multiple column definitions generated by
#' various functions into a single named list suitable for use in a Reactable table. It takes
#' multiple sets of column definitions as input and combines them into a single named list.
#'
#' @param ... Multiple sets of column definitions generated by functions like \code{colDef_sticky},
#'            \code{colDef_hide}, \code{colDef_minwidth}, etc.
#' @return A named list of combined column definitions suitable for use in a Reactable table.
#' @export
#' @examples
#'
#' mtcars %>%
#'   rownames_to_column("cars") %>%
#'   reactable(
#'     defaultColDef = colDef(footerStyle = list(fontWeight = "bold")),
#'     groupBy = "cars",
#'     columns = combined_named_lists(
#'       colDef_sticky(cols = c("cars", "mpg"))
#'       ,colDef_hide(cols = c("vs", "am", "gear", "carb", "wt"))
#'     )
#'   )
combined_named_lists <- function(...){
  item_list = list(...)
  keys <- unique(unlist(map(item_list, names)))

  combined = keys %>%
    map(~{
      tmp = .x
      flatten(map(item_list, ~.x[[tmp]]))
    }) %>%
    setNames(., keys)

  return(combined)
}
